### ISSUE TITLE
Error when compiling (scons) label:bug

### ISSUE THREAD

**Issue by 3dgoose** [MolassesLover/SpamtonOS#2]
When I try to compile the Operating System with the scons command (In the same directory than SConstruct), it outputs an error for Colorama.
```bash

ModuleNotFoundError: No module named 'colorama':
  File "/c/Dev/OS/SpamtOS/SConstruct", line 5:
    import colorama
```

**Comment by MolassesLover** [comment]
This error message just means you don't have [Colorama ](https://pypi.org/project/colorama/)installed, as such it's not a bug.
