### ISSUE TITLE
Same issue, with Arch this time

### ISSUE THREAD

**Issue by 3dgoose** [MolassesLover/SpamtonOS#4]
I have a fresh download of Arch, and downloaded SpamtOS. Just tried to compile with scons after steps and just appeared that I don't have Colorama. Pip install colorama, no PIP on computer. How to fix ?

**Comment by t3mp0r4ry23** [comment]
to install colorama you can ether:
1) install colorama directly (`pacman -S python-colorama`)
or
2) install pip (`pacman -S python-pip`) and then install colorama with pip (`pip install colorama`)

**Comment by MolassesLover** [comment]
Yeah, please take a look at what @t3mp0r4ry23 said. If `pacman -S python-colorama` doesn't work, use `pacman -Sy` to sync your repositories.

I think [this entry](https://wiki.archlinux.org/title/pacman#Installing_packages) in the Arch wiki might be helpful. 

If you have any trouble building let me know, Arch has a pretty inconsistent ABI.
